server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true # console sql display

  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG